🐶 Sync 2026-01-17 20:03:24

diff --git a/luci-app-packagesync/root/etc/init.d/packagesync b/luci-app-packagesync/root/etc/init.d/packagesync
--- a/luci-app-packagesync/root/etc/init.d/packagesync
+++ b/luci-app-packagesync/root/etc/init.d/packagesync
@@ -106,7 +106,6 @@ sync_instance() {
 	procd_open_instance 'sync'
 	procd_set_param command "$SYNCEXE" -o "$1"
 	procd_append_param command -l "$bwlimit" -d "$homepath" ${ALL_PROXY:+-x $ALL_PROXY} \
-		${GLOBAL_download_url:+--downloadurl "$GLOBAL_download_url"} \
 		${GLOBAL_rsync_url:+--rsyncurl "$GLOBAL_rsync_url"}
 	#procd_set_param respawn
 	#procd_set_param stdout 1
@@ -154,92 +153,101 @@ start_service() {
 }
 
 getinfo() {
-validate_section_config "$SCONFIG" define_global
-local rawhtml stables releases targets pkgarchs download_url="${GLOBAL_download_url:-$DOWNLOAD_URL}"
-# Versions
-rawhtml="$(curl --connect-timeout 10 --retry 3 -sSL "$download_url/")"
-stables="$( \
-echo "$rawhtml" | sed -n '/Stable Release/,/Development Snapshots/p' \
-| sed -n '/<ul>/,/<\/ul>/p' | grep 'OpenWrt' \
-| sed -E "s|.+\breleases/([^/]+)/.+|\1|g" \
-)"
-releases="$( \
-echo "$rawhtml" | sed -n '/Release Archive/,/\$/p' \
-| sed -n '/<ul>/,/<\/ul>/p' | grep 'OpenWrt' \
-| sed -E "s|.+\breleases/([^/]+)/.+|\1|g" \
-)"
-mkdir -p "${RELEASES_LIST%/*}" 2>/dev/null
-echo -e "Releases:"
-echo -e "$stables\n$releases"
-echo -e "$stables\n$releases" > "$RELEASES_LIST"
-# Targets
-rawhtml="$(curl --connect-timeout 10 --retry 3 -sSL "$download_url/$URLHREF_RELEASES/$(head -n1 <<< "$stables")/$URLHREF_VERS_TARGETS/")"
-targets="$( \
-echo "$rawhtml" \
-| sed -n '/<table>/,/<\/table>/p' | grep '<a href=' \
-| sed -E "s|.+\bhref=\"([^/]+)/.+|\1|g" \
-)"
-## subTargets
-fulltargets="$( \
-for target in $targets; do
-	subtargets="$(curl -sL "$download_url/$URLHREF_RELEASES/$(head -n1 <<< "$stables")/$URLHREF_VERS_TARGETS/$target/" \
-		| sed -n '/<table>/,/<\/table>/p' | grep '<a href=' \
-		| sed -E "s|.+\bhref=\"([^/]+)/.+|\1|g" \
+	validate_section_config "$SCONFIG" define_global
+	local rawhtml stables releases targets pkgarchs download_url="${GLOBAL_download_url:-$DOWNLOAD_URL}"
+
+	# Versions
+	rawhtml="$(curl --connect-timeout 10 --retry 3 -sSL "$download_url/")"
+	stables="$( \
+	echo "$rawhtml" | sed -n '/Stable Release/,/Development Snapshots/p' \
+	| sed -n '/<ul>/,/<\/ul>/p' | grep 'OpenWrt' \
+	| sed -E "s|.+\breleases/([^/]+)/.+|\1|g" \
 	)"
-	for subtarget in $subtargets; do sed "s|^|$target/|" <<< "$subtarget"; done
-done \
-)"
-mkdir -p "${TARGETS_LIST%/*}" 2>/dev/null
-echo "Targets:"
-echo "$fulltargets"
-echo "$fulltargets" > "$TARGETS_LIST"
-# Archs
-rawhtml="$(curl --connect-timeout 10 --retry 3 -sSL "$download_url/$URLHREF_RELEASES/$(head -n1 <<< "$stables")/$URLHREF_VERS_PACKAGES/")"
-pkgarchs="$( \
-echo "$rawhtml" \
-| sed -n '/<table>/,/<\/table>/p' | grep '<a href=' \
-| sed -E "s|.+\bhref=\"([^/]+)/.+|\1|g" \
-)"
-mkdir -p "${PKGARCHS_LIST%/*}" 2>/dev/null
-echo "PKGArchs:"
-echo "$pkgarchs"
-echo "$pkgarchs" > "$PKGARCHS_LIST"
+	releases="$( \
+	echo "$rawhtml" | sed -n '/Release Archive/,/\$/p' \
+	| sed -n '/<ul>/,/<\/ul>/p' | grep 'OpenWrt' \
+	| sed -E "s|.+\breleases/([^/]+)/.+|\1|g" \
+	)"
+	mkdir -p "${RELEASES_LIST%/*}" 2>/dev/null
+	echo -e "Releases:"
+	echo -e "$stables\n$releases"
+	echo -e "$stables\n$releases" > "$RELEASES_LIST"
+
+	# Targets
+	for stable in $stables; do
+		rawhtml="$(curl --connect-timeout 10 --retry 3 -sSL "$download_url/$URLHREF_RELEASES/$stable/$URLHREF_VERS_TARGETS/")"
+		targets="$( \
+		echo "$rawhtml" \
+		| grep -E '<a href=.+\d+:\d+' \
+		| sed -E "s|.+\bhref=\"([^/]+)/.+|\1|g" \
+		)"
+		## subTargets
+		fulltargets="$( \
+		for target in $targets; do
+			subtargets="$(curl -sL "$download_url/$URLHREF_RELEASES/$stable/$URLHREF_VERS_TARGETS/$target/" \
+			| grep -E '<a href=.+\d+:\d+' \
+			| sed -E "s|.+\bhref=\"([^/]+)/.+|\1|g" \
+			)"
+			for subtarget in $subtargets; do sed "s|^|$target/|" <<< "$subtarget"; done
+		done \
+		)"
+		fulltargetss="$(echo -e "$fulltargetss\n$fulltargets" | sort -u | grep -v '^$')"
+	done
+	mkdir -p "${TARGETS_LIST%/*}" 2>/dev/null
+	echo "Targets:"
+	echo "$fulltargetss"
+	echo "$fulltargetss" > "$TARGETS_LIST"
+
+	# Archs
+	for stable in $stables; do
+		rawhtml="$(curl --connect-timeout 10 --retry 3 -sSL "$download_url/$URLHREF_RELEASES/$stable/$URLHREF_VERS_PACKAGES/")"
+		pkgarchs="$( \
+		echo "$rawhtml" \
+		| grep -E '<a href=.+\d+:\d+' \
+		| sed -E "s|.+\bhref=\"([^/]+)/.+|\1|g" \
+		)"
+		pkgarchss="$(echo -e "$pkgarchss\n$pkgarchs" | sort -u | grep -v '^$')"
+	done
+	mkdir -p "${PKGARCHS_LIST%/*}" 2>/dev/null
+	echo "PKGArchs:"
+	echo "$pkgarchss"
+	echo "$pkgarchss" > "$PKGARCHS_LIST"
 }
 
 gethome() {
-home_url="${1:-$(uci -q get $CONFIG_NAME.$SCONFIG.home_url)}"
-home_url="${home_url:-$DEF_HOMEURL}"
-home_path="/www/$home_url"
+	home_url="${1:-$(uci -q get $CONFIG_NAME.$SCONFIG.home_url)}"
+	home_url="${home_url:-$DEF_HOMEURL}"
+	home_path="/www/$home_url"
 }
 
 checkln() {
-gethome
+	gethome
 
-# clean up old symlink
-ls -l /www|grep "\-> $MNTPKGS"|grep -v " $home_url -> $MNTPKGS"|sed -En "s,.+ ('.+'|\S+) -> ${MNTPKGS}$,'/www/\1',p" | xargs rm -f
-# show occupied
-find /www/* ! -type l -maxdepth 0|sed "s|.*/||g"
+	# clean up old symlink
+	ls -l /www | grep "\-> $MNTPKGS" | grep -v " $home_url -> $MNTPKGS" | sed -En "s,.+ ('.+'|\S+) -> ${MNTPKGS}$,'/www/\1',p" | xargs rm -f
+	# show occupied
+	find /www/* ! -type l -maxdepth 0 | sed "s|.*/||g"
 }
 
 symln() {
-gethome "$1"
+	gethome "$1"
 
-# make mount dir
-[ -e "$home_path" ] || { ln -s "$MNTPKGS" "$home_path" 2>/dev/null; ln -s "$RESULTPATH" "$home_path/results" 2>/dev/null; return 0; }
-[ -L "$home_path" ] || { >&2 echo "The Name $home_url is already used, please use another name"; return 1; }
-[ -n "$(ls -l "$home_path"|grep " $home_path -> $MNTPKGS")" ] || { >&2 echo "The Name $home_url is already used, please use another name"; return 1; }
-return 0
+	# make mount dir
+	[ -e "$home_path" ] || { ln -s "$MNTPKGS" "$home_path" 2>/dev/null; ln -s "$RESULTPATH" "$home_path/results" 2>/dev/null; return 0; }
+	[ -L "$home_path" ] || { >&2 echo "The Name $home_url is already used, please use another name"; return 1; }
+	[ -n "$(ls -l "$home_path" | grep " $home_path -> $MNTPKGS")" ] || { >&2 echo "The Name $home_url is already used, please use another name"; return 1; }
+	return 0
 }
 
 setcron() {
-local cron="$1" exist=$(cat "$CRONTABS" | sed -n "/\/etc\/init.d\/packagesync start/=")
+	local cron="$1" exist=$(cat "$CRONTABS" | sed -n "/\/etc\/init.d\/packagesync start/=")
 
-if [ -n "$cron" ]; then
-	[ -n "$exist" ] && sed -i "/\/etc\/init.d\/packagesync start/d" "$CRONTABS"
-	sed -i "\$a$cron /etc/init.d/packagesync start" "$CRONTABS"
-else
-	[ -n "$exist" ] && sed -i "/\/etc\/init.d\/packagesync start/d" "$CRONTABS"
-fi
+	if [ -n "$cron" ]; then
+		[ -n "$exist" ] && sed -i "/\/etc\/init.d\/packagesync start/d" "$CRONTABS"
+		sed -i "\$a$cron /etc/init.d/packagesync start" "$CRONTABS"
+	else
+		[ -n "$exist" ] && sed -i "/\/etc\/init.d\/packagesync start/d" "$CRONTABS"
+	fi
 }
 
 cleanup_regex() {
@@ -250,35 +258,35 @@ cleanup_regex() {
 }
 
 cleanup() {
-local autorm="$1"
-gethome
+	local autorm="$1"
+	gethome
 
-local count targets packages pkgarchs
-[ -d "$home_path/$URLHREF_RELEASES" ] || return 1
+	local count targets packages pkgarchs
+	[ -d "$home_path/$URLHREF_RELEASES" ] || return 1
 
-config_foreach validate_section_release $RELEASE cleanup_regex || return $?
+	config_foreach validate_section_release $RELEASE cleanup_regex || return $?
 
-#count=$(uci -q show $CONFIG_NAME|grep "=$RELEASE"|sed -E "s|.+@$RELEASE\[(\d+)\].+|\1|"|tail -n1)
-#
-#local ucivv="version target pkgarch"
-#for i in $(seq 0 $count); do
-#	for _var in $ucivv; do
-#		eval "local $_var=\$(uci -q get $CONFIG_NAME.@$RELEASE[$i].$_var)"
-#	done
-#	targets="${targets:+$targets|}/$version/$URLHREF_VERS_TARGETS/$target\b"
-#	packages="${packages:+$packages|}/$version/$URLHREF_VERS_PACKAGES\b"
-#	pkgarchs="${pkgarchs:+$pkgarchs|}/$URLHREF_PACKAGES_PREFIX${version%\.*}/$pkgarch\b"
-#done
-#echo "$targets"
-#echo "$packages"
-#echo "$pkgarchs"
+	#count=$(uci -q show $CONFIG_NAME|grep "=$RELEASE"|sed -E "s|.+@$RELEASE\[(\d+)\].+|\1|"|tail -n1)
+	#
+	#local ucivv="version target pkgarch"
+	#for i in $(seq 0 $count); do
+	#	for _var in $ucivv; do
+	#		eval "local $_var=\$(uci -q get $CONFIG_NAME.@$RELEASE[$i].$_var)"
+	#	done
+	#	targets="${targets:+$targets|}/$version/$URLHREF_VERS_TARGETS/$target\b"
+	#	packages="${packages:+$packages|}/$version/$URLHREF_VERS_PACKAGES\b"
+	#	pkgarchs="${pkgarchs:+$pkgarchs|}/$URLHREF_PACKAGES_PREFIX${version%\.*}/$pkgarch\b"
+	#done
+	#echo "$targets"
+	#echo "$packages"
+	#echo "$pkgarchs"
 
-local rm_path="$(\
-find $home_path/$URLHREF_RELEASES/* -type d -o -type l -maxdepth 3|grep -Ev "$targets"|grep -Ev "$packages"|grep -Ev "$pkgarchs"\
-|grep -E "(/\d+\.\d+[^/]*/($URLHREF_VERS_PACKAGES|$URLHREF_VERS_TARGETS/[^/]+/[^/]+)\$|/${URLHREF_PACKAGES_PREFIX}\d+\.\d+/[^/]+\$)"\
-)"
-sed "s|^/|rm '/|g;s|$|'|g" <<< "$rm_path"
-[ -z "$autorm" ] && return 0 || echo "$rm_path" | xargs rm -rf
+	local rm_path="$( \
+	find $home_path/$URLHREF_RELEASES/* -type d -o -type l -maxdepth 3 | grep -Ev "$targets" | grep -Ev "$packages" | grep -Ev "$pkgarchs" \
+	| grep -E "(/\d+\.\d+[^/]*/($URLHREF_VERS_PACKAGES|$URLHREF_VERS_TARGETS/[^/]+/[^/]+)\$|/${URLHREF_PACKAGES_PREFIX}\d+\.\d+/[^/]+\$)" \
+	)"
+	sed "s|^/|rm -rf '/|g;s|$|'|g" <<< "$rm_path"
+	[ -z "$autorm" ] && return 0 || echo "$rm_path" | xargs rm -rf
 
 }
 
diff --git a/luci-app-packagesync/root/usr/libexec/packagesync/sync b/luci-app-packagesync/root/usr/libexec/packagesync/sync
--- a/luci-app-packagesync/root/usr/libexec/packagesync/sync
+++ b/luci-app-packagesync/root/usr/libexec/packagesync/sync
@@ -15,7 +15,6 @@ JSON=''
 RESULTPATH='/var/packagesync/results'
 PIDFILE='/var/run/packagesync.pid'
 # url path
-DOWNLOAD_URL="https://downloads.openwrt.org"
 RSYNC_URL="rsync://rsync.openwrt.org/downloads"
 URLHREF_RELEASES='releases'
 #URLHREF_SNAPSHOTS='snapshots'
@@ -32,7 +31,7 @@ BWLIMIT='8000'
 
 
 # Get parameters
-GETOPT=$(getopt -n $(basename $0) -o d:n:s:t:k:m:e:o:l:x:V -l homedir:,name:,version:,target:,arch:,model:,extra:,orders:,bwlimit:,proxy:,downloadurl:,rsyncurl:,Version,help -- "$@")
+GETOPT=$(getopt -n $(basename $0) -o d:n:s:t:k:m:e:o:l:x:V -l homedir:,name:,version:,target:,arch:,model:,extra:,orders:,bwlimit:,proxy:,rsyncurl:,Version,help -- "$@")
 [ $? -ne 0 ] && >&2 echo -e "\tUse the --help option get help" && exit 1
 eval set -- "$GETOPT"
 OPTIONS=$(sed -E "s|'[^']*'||g; s| --( .*)?$||" <<< "$GETOPT")
@@ -82,7 +81,6 @@ Options:\n\
   -o, --orders <orders>               -- Required option. Sync multi-versions at once\n\
   -l, --bwlimit <n>[(K|M|G)]          -- Bandwidth limit\n\
   -x, --proxy <protocol://ip:port>    -- Connect using proxy\n\
-  --downloadurl <url>                 -- Optional option. Download url\n\
   --rsyncurl <url>                    -- Optional option. Rsync url\n\
   -V, --Version                       -- Returns version\n\
   --help                              -- Returns help info\n\
@@ -109,11 +107,11 @@ verify_path() {
 verify_order() {
   local version="$1" target="$2" arch="$3"
 
-  local HTTPCODE ERROR=0
-  HTTPCODE="$(curl --connect-timeout 10 --retry 3 -sSIL -w "%{http_code}" -o /dev/null "$DOWNLOAD_URL/$URLHREF_RELEASES/${version:-null}/$URLHREF_VERS_TARGETS/${target:-null}")"
-  [ -n "$(sed -n '/^2\d\d$/p' <<< "$HTTPCODE")" ] || { >&2 echo -e "$(basename $0): Get '$DOWNLOAD_URL/$URLHREF_RELEASES/${version:-<null>}/$URLHREF_VERS_TARGETS/${target:-<null>}' failed. Code '$HTTPCODE'"; ((ERROR++)); }
-  HTTPCODE="$(curl --connect-timeout 10 --retry 3 -sSIL -w "%{http_code}" -o /dev/null "$DOWNLOAD_URL/$URLHREF_RELEASES/${version:-null}/$URLHREF_VERS_PACKAGES/${arch:-null}")"
-  [ -n "$(sed -n '/^2\d\d$/p' <<< "$HTTPCODE")" ] || { >&2 echo -e "$(basename $0): Get '$DOWNLOAD_URL/$URLHREF_RELEASES/${version:-<null>}/$URLHREF_VERS_PACKAGES/${arch:-<null>}' failed. Code '$HTTPCODE'"; ((ERROR++)); }
+  local ERRORCODE ERROR=0
+  rsync --quiet --list-only        "$RSYNC_URL/$URLHREF_RELEASES/${version:-null}/$URLHREF_VERS_TARGETS/${target:-null}" 2>/dev/null || { ERRORCODE=$?;
+  >&2 echo -e "$(basename $0): Get '$RSYNC_URL/$URLHREF_RELEASES/${version:-<null>}/$URLHREF_VERS_TARGETS/${target:-<null>}' failed. Code '$ERRORCODE'"; ((ERROR++)); }
+  rsync --quiet --list-only        "$RSYNC_URL/$URLHREF_RELEASES/${version:-null}/$URLHREF_VERS_PACKAGES/${arch:-null}" 2>/dev/null || { ERRORCODE=$?;
+  >&2 echo -e "$(basename $0): Get '$RSYNC_URL/$URLHREF_RELEASES/${version:-<null>}/$URLHREF_VERS_PACKAGES/${arch:-<null>}' failed. Code '$ERRORCODE'"; ((ERROR++)); }
 
   [ "$ERROR" -gt 0 ] && return 1
   return 0
@@ -246,11 +244,15 @@ sync_extra() {
 
   mkdir -p "$home/${VER}/$URLHREF_VERS_TARGETS/$target" 2>/dev/null
   #supplementary
-  local table="$(curl --connect-timeout 10 --retry 3 -sSL "$DOWNLOAD_URL/${VER}/$URLHREF_VERS_TARGETS/$target" | sed -n '/Supplementary Files/,$p' | sed -n '/<table>/,/<\/table>/p')"
+  local table="$(rsync --list-only "$RSYNC_URL/${VER}/$URLHREF_VERS_TARGETS/$target/" | awk '{print $NF}' \
+    | grep -Ev '^\.{0,2}/?$' \
+    | grep -Ev '^(kmods|packages)/?$' \
+    | grep -Ev "^.*-${ver}-${target/\//-}-.*$" \
+  )"
   if [ -n "$table" ]; then
-    local expr="{$(echo "$table" | sed -En "s|.+\bhref=\"([^\"/]+)\".+|'\1'|gp" | tr '\n' ',' | sed 's|,$||')}"
+    local expr="{$(echo "$table" | sed "s|^|'|;s|$|'|" | tr '\n' ',' | sed 's|,$||')}"
     eval "rsync \$ARCHIVE\$INFO \$COMPAC \$PRUNE \$PROGR --bwlimit=\$BWLIMIT --include=$expr --exclude='*' \"\$RSYNC_URL/\${VER}/\$URLHREF_VERS_TARGETS/\$target/\" \"\$home/\${VER}/\$URLHREF_VERS_TARGETS/\$target/\"" || ((ERROR++))
-    #for v in $(echo "$table" | sed -En "s|.+\bhref=\"([^\"/]+)\".+|'\1'|gp"); do
+    #for v in $(echo "$table" | sed "s|^|'|;s|$|'|"); do
     #  rsync $ARCHIVE$INFO $COMPAC $PRUNE $PROGR --bwlimit=$BWLIMIT "$RSYNC_URL/${VER}/$URLHREF_VERS_TARGETS/$target/${v:1:-1}" "$home/${VER}/$URLHREF_VERS_TARGETS/$target/" || ((ERROR++))
     #done
   else
@@ -342,10 +344,6 @@ fe80:(:[[:xdigit:]]{0,4}){0,4}%\w+|\
     -l|--bwlimit)
       [ -n "$(echo "${2^^}"|sed -En '/^(\d|[1-9]\d*(K|M|G)?)$/p')" ] && BWLIMIT="${2^^}" || { >&2 echo -e "$(basename $0): Option '$1' requires a valid argument\n\tUse the --help option get help"; exit 1; }
       #[ -n "$(echo "$2"|sed -En '/^(\d|[1-9]\d*(K|M|G)?)$/lp')" ]
-      shift
-    ;;
-    --downloadurl)
-      DOWNLOAD_URL="$2"
       shift
     ;;
     --rsyncurl)
