⛄ Sync 2024-10-24 20:34:52

diff --git a/luci-app-pppoe-user/root/etc/ppp/ip-down.d/speed-limit b/luci-app-pppoe-user/root/etc/ppp/ip-down.d/speed-limit
--- a/luci-app-pppoe-user/root/etc/ppp/ip-down.d/speed-limit
+++ b/luci-app-pppoe-user/root/etc/ppp/ip-down.d/speed-limit
@@ -1,39 +1,44 @@
 #!/bin/sh
-#
-# This script is run by the pppd after the link is established.
-# It should be used to add routes, set IP address, run the mailq
-# etc.
-#
-# This script is called with the following arguments:
-#    Arg  Name               Example
-#    $1   Interface name     ppp0
-#    $2   The tty            ttyS1
-#    $3   The link speed     38400
-#    $4   Local IP number    12.34.56.78
-#    $5   Peer  IP number    12.34.56.99
-#
+(
+  flock -n 200 || exit 1
 
-#
-# The  environment is cleared before executing this script
-# so the path must be reset
-#
-PATH=/usr/sbin:/sbin:/usr/bin:/bin
-export PATH
+  # The environment is cleared before executing this script
+  PATH=/usr/sbin:/sbin:/usr/bin:/bin
+  export PATH
 
-QUIT_TIME="$(date "+%Y-%m-%d_%H:%M:%S")"
-USERNAME="${PEERNAME}"
-PEERIP="${5}"
+  QUIT_TIME="$(date "+%Y-%m-%d_%H:%M:%S")"
+  USERNAME="${PEERNAME}"
+  PEERIP="${5}"
 
-USER_CONFIG="pppoe-user"
-USER_CFGID="$(uci show ${USER_CONFIG} | grep "${USERNAME}" | cut -d '.' -sf 2)"
-UP="upload"
-DOWN="download"
-UPLOAD_HANDLE="$(nft -a list chain inet pppoe-user-qos ${UP} | grep "${PEERIP}" | awk '{print $NF}')"
-DOWNLOAD_HANDLE="$(nft -a list chain inet pppoe-user-qos ${DOWN} | grep "${PEERIP}" | awk '{print $NF}')"
+  USER_CONFIG="pppoe-user"
+  USER_CFGID="$(uci show ${USER_CONFIG} | grep "${USERNAME}" | cut -d '.' -sf 2)"
+  UP="upload"
+  DOWN="download"
 
-nft delete rule inet pppoe-user-qos ${UP} handle "${UPLOAD_HANDLE}"
-nft delete rule inet pppoe-user-qos ${DOWN} handle "${DOWNLOAD_HANDLE}"
+  # Get the handles for the rate limit rules
+  UPLOAD_HANDLE="$(nft -a list chain inet pppoe ${UP} | grep "${PEERIP}" | awk '{print $NF}')"
+  DOWNLOAD_HANDLE="$(nft -a list chain inet pppoe ${DOWN} | grep "${PEERIP}" | awk '{print $NF}')"
 
-logger "${QUIT_TIME} ${PEERNAME} ${PEERIP} SPEED-LIMIT >>>>>> The script has been executed!"
+  # Remove upload rule
+  if [ -n "${UPLOAD_HANDLE}" ]; then
+      nft delete rule inet pppoe ${UP} handle "${UPLOAD_HANDLE}" || {
+          logger "${QUIT_TIME} ERROR: Failed to delete upload rule for ${PEERIP}"
+          exit 1
+      }
+  else
+      logger "${QUIT_TIME} WARNING: No upload rule found for ${PEERIP}"
+  fi
 
-exit 0
+  # Remove download rule
+  if [ -n "${DOWNLOAD_HANDLE}" ]; then
+      nft delete rule inet pppoe ${DOWN} handle "${DOWNLOAD_HANDLE}" || {
+          logger "${QUIT_TIME} ERROR: Failed to delete download rule for ${PEERIP}"
+          exit 1
+      }
+  else
+      logger "${QUIT_TIME} WARNING: No download rule found for ${PEERIP}"
+  fi
+
+  exit 0
+
+) 200>/var/lock/ipdown.lock
diff --git a/luci-app-pppoe-user/root/etc/ppp/ip-up b/luci-app-pppoe-user/root/etc/ppp/ip-up
--- a/luci-app-pppoe-user/root/etc/ppp/ip-up
+++ b/luci-app-pppoe-user/root/etc/ppp/ip-up
@@ -1,30 +1,41 @@
 #!/bin/sh
-#
-# This script is run by the pppd after the link is established.
-# It should be used to add routes, set IP address, run the mailq etc.
-#
-# This script is called with the following arguments:
-# Arg  Name               Example
-# $1   Interface name     ppp0
-# $2   The tty            ttyS1
-# $3   The link speed     38400
-# $4   Local IP number    12.34.56.78
-# $5   Peer  IP number    12.34.56.99
-#
 
-#
-# The environment is cleared before executing this script
-# so the path must be reset
-#
+# This script is run by the pppd after the link is established.
+# It should be used to add routes, set IP address, run the mailq, etc.
+
+# Check if the required number of arguments is provided
+if [ $# -ne 5 ]; then
+    echo "Usage: $0 <interface> <tty> <speed> <local_ip> <peer_ip>" >&2
+    exit 1
+fi
+
+# Reset the PATH variable
 PATH=/usr/sbin:/sbin:/usr/bin:/bin
 export PATH
 
-# Loop through all files in the ip-up.d directory and execute them if they are executable
+# Log the start of the script
+logger "Starting ip-up script for interface $1 with local IP $4 and peer IP $5"
+
+# Define the directory containing additional scripts
 IP_UP_D_DIR="/etc/ppp/ip-up.d"
+
+# Check if the directory exists
+if [ ! -d "$IP_UP_D_DIR" ]; then
+    echo "Directory $IP_UP_D_DIR does not exist." >&2
+    exit 1
+fi
+
+# Loop through all files in the ip-up.d directory and execute them if they are executable
 for script in "$IP_UP_D_DIR"/*; do
     if [ -x "$script" ]; then
-        "$script" "$@"
+        "$script" "$@" || {
+            echo "Error executing $script" >&2
+            exit 1
+        }
     fi
 done
+
+# Log the successful completion of the script
+logger "Completed ip-up script for interface $1"
 
 exit 0
diff --git a/luci-app-pppoe-user/root/etc/ppp/ip-up.d/speed-limit b/luci-app-pppoe-user/root/etc/ppp/ip-up.d/speed-limit
--- a/luci-app-pppoe-user/root/etc/ppp/ip-up.d/speed-limit
+++ b/luci-app-pppoe-user/root/etc/ppp/ip-up.d/speed-limit
@@ -1,42 +1,45 @@
 #!/bin/sh
-#
-# This script is run by the pppd after the link is established.
-# It should be used to add routes, set IP address, run the mailq etc.
-#
-# This script is called with the following arguments:
-# Arg  Name               Example
-# $1   Interface name     ppp0
-# $2   The tty            ttyS1
-# $3   The link speed     38400
-# $4   Local IP number    12.34.56.78
-# $5   Peer  IP number    12.34.56.99
-#
+(
+  flock -n 200 || exit 1
 
-#
-# The environment is cleared before executing this script
-# so the path must be reset
-#
-PATH=/usr/sbin:/sbin:/usr/bin:/bin
-export PATH
+  # Environment variable settings
+  PATH=/usr/sbin:/sbin:/usr/bin:/bin
+  export PATH
 
-LOGIN_TIME="$(date "+%Y-%m-%d_%H:%M:%S")"
-USERNAME="${PEERNAME}"
-PEERIP="${5}"
+  LOGIN_TIME="$(date "+%Y-%m-%d_%H:%M:%S")"
+  USERNAME="${PEERNAME}"
+  PEERIP="${5}"
 
-USER_CONFIG="pppoe-user"
-USER_CFGID="$(uci show ${USER_CONFIG} | grep "${USERNAME}" | cut -d '.' -sf 2)"
-USER_QOS="$(uci get ${USER_CONFIG}."${USER_CFGID}".qos)"
-USER_UPLOAD="$(uci get ${USER_CONFIG}."${USER_CFGID}".urate)"
-USER_DOWNLOAD="$(uci get ${USER_CONFIG}."${USER_CFGID}".drate)"
-USER_UNIT="$(uci get ${USER_CONFIG}."${USER_CFGID}".unit)"
-UP="upload"
-DOWN="download"
+  USER_CONFIG="pppoe-user"
+  USER_CFGID="$(uci show ${USER_CONFIG} | grep "${USERNAME}" | cut -d '.' -sf 2)"
+  
+  # Get user configuration
+  USER_QOS="$(uci get ${USER_CONFIG}.${USER_CFGID}.qos 2>/dev/null)"
+  USER_UPLOAD="$(uci get ${USER_CONFIG}.${USER_CFGID}.urate 2>/dev/null)"
+  USER_DOWNLOAD="$(uci get ${USER_CONFIG}.${USER_CFGID}.drate 2>/dev/null)"
+  USER_UNIT="$(uci get ${USER_CONFIG}.${USER_CFGID}.unit 2>/dev/null)"
 
-if [ "${USER_QOS}" = "1" ]; then
-nft insert rule inet pppoe-user-qos ${UP} ip saddr "${PEERIP}" limit rate over "${USER_UPLOAD}" "${USER_UNIT}"/second drop
-nft insert rule inet pppoe-user-qos ${DOWN} ip daddr "${PEERIP}" limit rate over "${USER_DOWNLOAD}" "${USER_UNIT}"/second drop
-fi
+  # Ensure that the obtained values are valid
+  if [ -z "${USER_QOS}" ] || [ -z "${USER_UPLOAD}" ] || [ -z "${USER_DOWNLOAD}" ] || [ -z "${USER_UNIT}" ]; then
+      logger "${LOGIN_TIME} ERROR: Failed to get user config for ${USERNAME} (${PEERIP})"
+      exit 1
+  fi
 
-logger "${LOGIN_TIME} ${PEERNAME} ${PEERIP} SPEED-LIMIT >>>>>> The script has been executed!"
+  UP="upload"
+  DOWN="download"
 
-exit 0
+  # Add traffic control rules
+  if [ "${USER_QOS}" = "1" ]; then
+      nft insert rule inet pppoe ${UP} ip saddr "${PEERIP}" limit rate over "${USER_UPLOAD}" "${USER_UNIT}"/second counter drop || {
+          logger "${LOGIN_TIME} ERROR: Invalid upload speed limit for IP ${PEERIP}"
+          exit 1
+      }
+      nft insert rule inet pppoe ${DOWN} ip daddr "${PEERIP}" limit rate over "${USER_DOWNLOAD}" "${USER_UNIT}"/second counter drop || {
+          logger "${LOGIN_TIME} ERROR: Invalid download speed limit for IP ${PEERIP}"
+          exit 1
+      }
+  fi
+
+  exit 0
+
+) 200>/var/lock/ipup.lock
