💐 Sync 2024-12-09 02:41:25

diff --git a/qosmate/etc/init.d/qosmate b/qosmate/etc/init.d/qosmate
--- a/qosmate/etc/init.d/qosmate
+++ b/qosmate/etc/init.d/qosmate
@@ -15,8 +15,10 @@ EXTRA_HELP="        check_version   Check for updates
         validate_custom_rules    Validate custom rules"
 
 REQUIRED_PACKAGES="kmod-sched ip-full kmod-veth tc-full kmod-netem kmod-sched-ctinfo kmod-ifb kmod-sched-cake kmod-sched-red luci-lib-jsonc lua"
-SCRIPT_URL="https://raw.githubusercontent.com/hudra0/qosmate/main/etc/qosmate.sh"
-HOTPLUG_SCRIPT_URL="https://raw.githubusercontent.com/hudra0/qosmate/main/etc/hotplug.d/iface/13-qosmateHotplug"
+
+# Base URL (raw) for repositories (can be overridden for different branches/commits)
+QOSMATE_BASE_URL="${QOSMATE_BASE_URL:-https://raw.githubusercontent.com/hudra0/qosmate/main}"
+QOSMATE_FRONTEND_BASE_URL="${QOSMATE_FRONTEND_BASE_URL:-https://raw.githubusercontent.com/hudra0/luci-app-qosmate/main}"
 
 load_config() {
     config_load 'qosmate'
@@ -57,10 +59,22 @@ detect_package_manager() {
     fi
 }
 
+# Check for valid package manager
+check_pkg_manager() {
+    case "$1" in
+        apk|opkg)
+            ;;
+        *)
+            logger -s -t qosmate -p user.err "Error: Unexpected package manager '$1'."
+            return 1
+            ;;
+    esac
+    :
+}
+
 # Check if a package is installed
 check_package() {
     local pkg="$1"
-    local pkg_manager=$(detect_package_manager)
     
     case "$pkg_manager" in
         "apk")
@@ -78,10 +92,11 @@ check_package() {
 }
 
 install_packages() {
-    local pkg_manager=$(detect_package_manager)
     # Flag to indicate if opkg update is needed    
     local need_update=0
-    
+
+    check_pkg_manager "$pkg_manager" || return 1
+
     # Check if any packages are missing
     for pkg in $REQUIRED_PACKAGES; do
         if ! check_package "$pkg"; then
@@ -130,7 +145,6 @@ install_packages() {
 }
 
 check_package_status() {
-    local pkg_manager=$(detect_package_manager)
     local missing_packages=""
     
     for pkg in $REQUIRED_PACKAGES; do
@@ -148,13 +162,13 @@ check_package_status() {
 }
 
 download_scripts() {
-    [ ! -f /etc/qosmate.sh ] && wget -O /etc/qosmate.sh $SCRIPT_URL && chmod a+x /etc/qosmate.sh
+    [ ! -f /etc/qosmate.sh ] && wget -O /etc/qosmate.sh "$QOSMATE_BASE_URL/etc/qosmate.sh" && chmod a+x /etc/qosmate.sh
     
     # Create the directory for tc-Netem distributions if it does not exist
     mkdir -p /usr/lib/tc
 
     # Base URL for the repository
-    DIST_URL="https://raw.githubusercontent.com/hudra0/qosmate/main/usr/lib/tc"
+    DIST_URL="$QOSMATE_BASE_URL/usr/lib/tc"
 
     # List of files
     DIST_FILES="experimental.dist normal.dist normmix20-64.dist pareto.dist paretonormal.dist"
@@ -173,16 +187,21 @@ create_hotplug_script() {
 #!/bin/sh
 
 [ -n "$DEVICE" ] || exit 0
-[ "$ACTION" = ifup ] && {
-    enabled=$(uci get qosmate.global.enabled 2>/dev/null)
-    if [ "$enabled" = "1" ]; then
+if [ "$ACTION" = ifup ]; then
+    . /lib/functions.sh
+    config_load qosmate || {
+        logger -t qosmate -p user.err "Failed to load config."
+        exit 1
+    }
+    config_get qosmate_enabled global enabled
+    if [ "$qosmate_enabled" = "1" ]; then
+        logger -t qosmate "Reloading qosmate.sh due to $ACTION of $INTERFACE ($DEVICE)"
         /etc/init.d/qosmate enable
         /etc/init.d/qosmate restart
-        logger -t qosmate "Reloading qosmate.sh due to $ACTION of $INTERFACE ($DEVICE)"
     else
         logger -t qosmate "qosmate is disabled in the configuration. Not executing the script."
     fi
-}
+fi
 EOF
 }
 
@@ -190,7 +209,7 @@ check_and_download_config() {
     local config_path="/etc/config/qosmate"
     if [ ! -f "$config_path" ]; then
         echo "Configuration file not found, downloading the latest version..."
-        wget -O $config_path "https://raw.githubusercontent.com/hudra0/qosmate/main/etc/config/qosmate" || {
+        wget -O $config_path "$QOSMATE_BASE_URL/etc/config/qosmate" || {
             echo "Error downloading configuration. Please check your internet connection and try again."
             return 1
         }
@@ -261,13 +280,13 @@ manage_custom_rules_file() {
 start_service() {
     install_packages
     download_scripts
-    create_hotplug_script  # Create the hotplug script instead of downloading it    
-    check_and_download_config || return 1    
-    migrate_config 
+    create_hotplug_script  # Create the hotplug script instead of downloading it
+    check_and_download_config || return 1
+    migrate_config
 
     # Enable the global option
     uci set qosmate.global.enabled='1'
-    uci commit qosmate    
+    uci commit qosmate
 
     # Save the current WAN interface to a temporary file
     load_config
@@ -275,12 +294,12 @@ start_service() {
 
     # Create custom rules file if it doesn't exist
     manage_custom_rules_file create
-    nft -f /etc/qosmate.d/custom_rules.nft    
+    nft -f /etc/qosmate.d/custom_rules.nft
 
-    /etc/qosmate.sh    
+    /etc/qosmate.sh
     /etc/init.d/firewall reload
-    echo "Service started" | logger -t qosmate    
-    /etc/init.d/qosmate enable     
+    logger -t qosmate "Service started"
+    /etc/init.d/qosmate enable
 }
 
 stop_service() {
@@ -311,7 +330,7 @@ stop_service() {
     ## Delete the old qdiscs and IFB associated with the old WAN interface
     tc qdisc del dev "$OLD_WAN" root > /dev/null 2>&1
     tc qdisc del dev ifb-"$OLD_WAN" root > /dev/null 2>&1
-    tc qdisc del dev "$OLD_WAN" ingress > /dev/null 2>&1 
+    tc qdisc del dev "$OLD_WAN" ingress > /dev/null 2>&1
 
     # Remove IFB interface
     ip link del ifb-"$OLD_WAN" 2>/dev/null
@@ -324,39 +343,38 @@ stop_service() {
     echo "Reloading network service..."
     /etc/init.d/network reload
     /etc/init.d/firewall reload
-    echo "Service stopped" | logger -t qosmate     
+    logger -t qosmate "Service stopped"
     exit 0
 }
 
 status_service() {
     # Load configuration
-    . /lib/functions.sh
     config_load 'qosmate'
 
     # Function to extract default values from the main script
     get_default_value() {
         local var_name="$1"
-        local default_value="$(grep "^$var_name=" /etc/qosmate.sh | cut -d'=' -f2- | tr -d '"')"
-        echo "$default_value"
+        grep "^$var_name=" /etc/qosmate.sh | cut -d'=' -f2- | tr -d '"'
     }
 
-    # Function to get current value or default
-    get_current_or_default() {
-        local uci_path="$1"
-        local default_value="$2"
-        local value="$(uci -q get "$uci_path")"
-        if [ -z "$value" ]; then
-            echo "$default_value (Default value)"
-        else
-            echo "$value"
-        fi
-    }
+    # Get current values, replace with defaults if not set
+    local WAN UPRATE DOWNRATE GAMEUP GAMEDOWN gameqdisc
+    config_get WAN settings WAN
+    : "${WAN:="$(get_default_value DEFAULT_WAN)"}"
+    config_get UPRATE settings UPRATE
+    : "${UPRATE:="$(get_default_value DEFAULT_UPRATE)"}"
+    config_get DOWNRATE settings DOWNRATE
+    : "${DOWNRATE:="$(get_default_value DEFAULT_DOWNRATE)"}"
 
-    # Extract default values
-    DEFAULT_WAN=$(get_default_value "DEFAULT_WAN")
-    DEFAULT_DOWNRATE=$(get_default_value "DEFAULT_DOWNRATE")
-    DEFAULT_UPRATE=$(get_default_value "DEFAULT_UPRATE")
-    DEFAULT_GAMEQDISC=$(get_default_value "gameqdisc")
+    config_get ROOT_QDISC settings ROOT_QDISC "hfsc"
+    config_get gameqdisc hfsc gameqdisc
+    : "${gameqdisc:="$(get_default_value DEFAULT_GAMEQDISC)"}"
+
+    # For default GAMEUP and GAMEDOWN, we need to evaluate the expressions
+    config_get GAMEUP hfsc GAMEUP
+    : "${GAMEUP:=$((UPRATE*15/100+400))}"
+    config_get GAMEDOWN hfsc GAMEDOWN
+    : "${GAMEDOWN:=$((DOWNRATE*15/100+400))}"
 
     echo "==== qosmate Status ===="
     
@@ -368,8 +386,7 @@ status_service() {
     fi
 
     # Check if traffic shaping is active
-    WAN=$(uci -q get qosmate.settings.WAN || echo "$DEFAULT_WAN")
-    IFB="ifb-$WAN"
+    local IFB="ifb-$WAN"
     
     if tc qdisc show dev "$WAN" 2>/dev/null | grep -q "qdisc cake"; then
         if /etc/init.d/qosmate enabled; then
@@ -400,25 +417,20 @@ status_service() {
 
     echo "==== Current Settings ===="
     # Show summary of current settings
-    echo "Upload rate: $(get_current_or_default qosmate.settings.UPRATE "$DEFAULT_UPRATE") kbps"
-    echo "Download rate: $(get_current_or_default qosmate.settings.DOWNRATE "$DEFAULT_DOWNRATE") kbps"
+    echo "Upload rate: $UPRATE kbps"
+    echo "Download rate: $DOWNRATE kbps"
     
-    # For GAMEUP and GAMEDOWN, we need to evaluate the expressions
-    UPRATE=$(uci -q get qosmate.settings.UPRATE || echo "$DEFAULT_UPRATE")
-    DOWNRATE=$(uci -q get qosmate.settings.DOWNRATE || echo "$DEFAULT_DOWNRATE")
-    DEFAULT_GAMEUP=$((UPRATE*15/100+400))
-    DEFAULT_GAMEDOWN=$((DOWNRATE*15/100+400))
-    
-    echo "Game traffic upload: $(get_current_or_default qosmate.hfsc.GAMEUP "$DEFAULT_GAMEUP") kbps"
-    echo "Game traffic download: $(get_current_or_default qosmate.hfsc.GAMEDOWN "$DEFAULT_GAMEDOWN") kbps"
-    if [ "$(get_current_or_default qosmate.settings.ROOT_QDISC "hfsc")" = "cake" ]; then
+    echo "Game traffic upload: $GAMEUP kbps"
+    echo "Game traffic download: $GAMEDOWN kbps"
+    if [ "$ROOT_QDISC" = "cake" ]; then
         echo "Queue discipline: CAKE (Root qdisc)"
     else
-        echo "Queue discipline: $(get_current_or_default qosmate.hfsc.gameqdisc "$DEFAULT_GAMEQDISC") (for game traffic in HFSC)"
+        echo "Queue discipline: $gameqdisc (for game traffic in HFSC)"
     fi
 
     echo "==== Package Status ===="
-    if check_package_status; then
+
+    if check_pkg_manager "$pkg_manager" && check_package_status; then
         echo "All required packages are installed."
     else
         echo "Some required packages are missing. QoSmate may not function correctly."
@@ -458,10 +470,10 @@ reload_service() {
 
 check_version() {
     local current_backend_version="$(grep '^VERSION=' /etc/qosmate.sh | cut -d'"' -f2)"
-    local latest_backend_version="$(wget -qO- https://raw.githubusercontent.com/hudra0/qosmate/main/etc/qosmate.sh | grep '^VERSION=' | cut -d'"' -f2)"
+    local latest_backend_version="$(wget -qO- "$QOSMATE_BASE_URL/etc/qosmate.sh" | grep '^VERSION=' | cut -d'"' -f2)"
     
     local current_frontend_version="$(grep '^const UI_VERSION' /www/luci-static/resources/view/qosmate/settings.js | cut -d"'" -f2)"
-    local latest_frontend_version="$(wget -qO- https://raw.githubusercontent.com/hudra0/luci-app-qosmate/main/htdocs/luci-static/resources/view/settings.js | grep '^const UI_VERSION' | cut -d"'" -f2)"
+    local latest_frontend_version="$(wget -qO- "$QOSMATE_FRONTEND_BASE_URL/htdocs/luci-static/resources/view/settings.js" | grep '^const UI_VERSION' | cut -d"'" -f2)"
     
     if [ -z "$latest_backend_version" ] || [ -z "$latest_frontend_version" ]; then
         echo "Error: Could not retrieve the latest versions."
@@ -494,10 +506,10 @@ update() {
     fi
 
     local current_backend_version="$(grep '^VERSION=' /etc/qosmate.sh | cut -d'"' -f2)"
-    local latest_backend_version="$(wget -qO- https://raw.githubusercontent.com/hudra0/qosmate/main/etc/qosmate.sh | grep '^VERSION=' | cut -d'"' -f2)"
+    local latest_backend_version="$(wget -qO- "$QOSMATE_BASE_URL/etc/qosmate.sh" | grep '^VERSION=' | cut -d'"' -f2)"
     
     local current_frontend_version="$(grep '^const UI_VERSION' /www/luci-static/resources/view/qosmate/settings.js | cut -d"'" -f2)"
-    local latest_frontend_version="$(wget -qO- https://raw.githubusercontent.com/hudra0/luci-app-qosmate/main/htdocs/luci-static/resources/view/settings.js | grep '^const UI_VERSION' | cut -d"'" -f2)"
+    local latest_frontend_version="$(wget -qO- "$QOSMATE_FRONTEND_BASE_URL/htdocs/luci-static/resources/view/settings.js" | grep '^const UI_VERSION' | cut -d"'" -f2)"
     
     if [ -z "$latest_backend_version" ] || [ -z "$latest_frontend_version" ]; then
         echo "Error: Could not retrieve the latest versions."
@@ -530,9 +542,9 @@ update() {
     # Update backend
     if [ "$force_update" -eq 1 ] || [ "$current_backend_version" != "$latest_backend_version" ]; then
         echo "Updating backend..."
-        if wget -O /etc/qosmate.sh https://raw.githubusercontent.com/hudra0/qosmate/main/etc/qosmate.sh && \
-           wget -O /etc/init.d/qosmate https://raw.githubusercontent.com/hudra0/qosmate/main/etc/init.d/qosmate && \
-           wget -O /etc/hotplug.d/iface/13-qosmateHotplug https://raw.githubusercontent.com/hudra0/qosmate/main/etc/hotplug.d/iface/13-qosmateHotplug; then
+        if wget -O /etc/qosmate.sh "$QOSMATE_BASE_URL/etc/qosmate.sh" && \
+           wget -O /etc/init.d/qosmate "$QOSMATE_BASE_URL/etc/init.d/qosmate" && \
+           wget -O /etc/hotplug.d/iface/13-qosmateHotplug "$QOSMATE_BASE_URL/etc/hotplug.d/iface/13-qosmateHotplug"; then
             chmod +x /etc/qosmate.sh /etc/init.d/qosmate
             echo "Backend update complete."
         else
@@ -544,16 +556,16 @@ update() {
     # Update frontend
     if [ "$force_update" -eq 1 ] || [ "$current_frontend_version" != "$latest_frontend_version" ]; then
         echo "Updating frontend..."
-        if  wget -O /www/luci-static/resources/view/qosmate/settings.js https://raw.githubusercontent.com/hudra0/luci-app-qosmate/main/htdocs/luci-static/resources/view/settings.js && \
-            wget -O /www/luci-static/resources/view/qosmate/hfsc.js https://raw.githubusercontent.com/hudra0/luci-app-qosmate/main/htdocs/luci-static/resources/view/hfsc.js && \
-            wget -O /www/luci-static/resources/view/qosmate/cake.js https://raw.githubusercontent.com/hudra0/luci-app-qosmate/main/htdocs/luci-static/resources/view/cake.js && \
-            wget -O /www/luci-static/resources/view/qosmate/advanced.js https://raw.githubusercontent.com/hudra0/luci-app-qosmate/main/htdocs/luci-static/resources/view/advanced.js && \
-            wget -O /www/luci-static/resources/view/qosmate/rules.js https://raw.githubusercontent.com/hudra0/luci-app-qosmate/main/htdocs/luci-static/resources/view/rules.js && \
-            wget -O /www/luci-static/resources/view/qosmate/connections.js https://raw.githubusercontent.com/hudra0/luci-app-qosmate/main/htdocs/luci-static/resources/view/connections.js && \
-            wget -O /www/luci-static/resources/view/qosmate/custom_rules.js https://raw.githubusercontent.com/hudra0/luci-app-qosmate/main/htdocs/luci-static/resources/view/custom_rules.js && \
-            wget -O /usr/share/luci/menu.d/luci-app-qosmate.json https://raw.githubusercontent.com/hudra0/luci-app-qosmate/main/root/usr/share/luci/menu.d/luci-app-qosmate.json && \
-            wget -O /usr/share/rpcd/acl.d/luci-app-qosmate.json https://raw.githubusercontent.com/hudra0/luci-app-qosmate/main/root/usr/share/rpcd/acl.d/luci-app-qosmate.json && \
-            wget -O /usr/libexec/rpcd/luci.qosmate https://raw.githubusercontent.com/hudra0/luci-app-qosmate/main/root/usr/libexec/rpcd/luci.qosmate; then
+        if  wget -O /www/luci-static/resources/view/qosmate/settings.js "$QOSMATE_FRONTEND_BASE_URL/htdocs/luci-static/resources/view/settings.js" && \
+            wget -O /www/luci-static/resources/view/qosmate/hfsc.js "$QOSMATE_FRONTEND_BASE_URL/htdocs/luci-static/resources/view/hfsc.js" && \
+            wget -O /www/luci-static/resources/view/qosmate/cake.js "$QOSMATE_FRONTEND_BASE_URL/htdocs/luci-static/resources/view/cake.js" && \
+            wget -O /www/luci-static/resources/view/qosmate/advanced.js "$QOSMATE_FRONTEND_BASE_URL/htdocs/luci-static/resources/view/advanced.js" && \
+            wget -O /www/luci-static/resources/view/qosmate/rules.js "$QOSMATE_FRONTEND_BASE_URL/htdocs/luci-static/resources/view/rules.js" && \
+            wget -O /www/luci-static/resources/view/qosmate/connections.js "$QOSMATE_FRONTEND_BASE_URL/htdocs/luci-static/resources/view/connections.js" && \
+            wget -O /www/luci-static/resources/view/qosmate/custom_rules.js "$QOSMATE_FRONTEND_BASE_URL/htdocs/luci-static/resources/view/custom_rules.js" && \
+            wget -O /usr/share/luci/menu.d/luci-app-qosmate.json "$QOSMATE_FRONTEND_BASE_URL/root/usr/share/luci/menu.d/luci-app-qosmate.json" && \
+            wget -O /usr/share/rpcd/acl.d/luci-app-qosmate.json "$QOSMATE_FRONTEND_BASE_URL/root/usr/share/rpcd/acl.d/luci-app-qosmate.json" && \
+            wget -O /usr/libexec/rpcd/luci.qosmate "$QOSMATE_FRONTEND_BASE_URL/root/usr/libexec/rpcd/luci.qosmate"; then
             chmod +x /usr/libexec/rpcd/luci.qosmate
             echo "Frontend update complete."
             /etc/init.d/rpcd restart
@@ -625,13 +637,14 @@ auto_setup() {
                 SPEEDTEST_CMD="speedtest --simple"
             else
                 echo "Neither speedtest-go nor python3-speedtest-cli is installed. Attempting to install speedtest-go..."
+                check_pkg_manager "$pkg_manager" || return 1
                 
                 # Check for sufficient space (adjust the required space as needed)
                 FREE_SPACE=$(df /overlay | awk 'NR==2 {print $4}')
                 if [ "$FREE_SPACE" -lt 15360 ]; then  # Assuming 15MB for speedtest-go
                     echo "Not enough space for speedtest-go. Attempting to install python3-speedtest-cli instead..."
                 else
-                    case "$(detect_package_manager)" in
+                    case "$pkg_manager" in
                         "apk")
                             apk update && apk add speedtest-go
                             ;;
@@ -653,7 +666,7 @@ auto_setup() {
                         echo "Auto-setup cannot continue. Please free up some space and try again."
                         return 1
                     fi
-                    case "$(detect_package_manager)" in
+                    case "$pkg_manager" in
                         "apk")
                             apk update && apk add python3-speedtest-cli
                             ;;
@@ -792,13 +805,14 @@ auto_setup_noninteractive() {
             SPEEDTEST_CMD="speedtest --simple"
         else
             echo "Neither speedtest-go nor python3-speedtest-cli is installed. Attempting to install speedtest-go..."
-            
+            check_pkg_manager "$pkg_manager" || return 1
+
             # Check for sufficient space (adjust the required space as needed)
             FREE_SPACE=$(df /overlay | awk 'NR==2 {print $4}')
             if [ "$FREE_SPACE" -lt 15360 ]; then  # Assuming 15MB for speedtest-go
                 echo "Not enough space for speedtest-go. Attempting to install python3-speedtest-cli instead..."
             else
-                case "$(detect_package_manager)" in
+                case "$pkg_manager" in
                     "apk")
                         apk update && apk add speedtest-go
                         ;;
@@ -820,7 +834,7 @@ auto_setup_noninteractive() {
                     echo "Auto-setup cannot continue. Please free up some space and try again."
                     return 1
                 fi
-                case "$(detect_package_manager)" in
+                case "$pkg_manager" in
                     "apk")
                         apk update && apk add python3-speedtest-cli
                         ;;
@@ -977,3 +991,5 @@ expand_config() {
 
     echo "Configuration expanded successfully. You can now edit all available options in $config_file"
 }
+
+pkg_manager="$(detect_package_manager)" # global variable
